version: "3"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - ./sql/conf/:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: site
      MYSQL_USER: local_user
      MYSQL_PASSWORD: local_password
  redis:
    image: redis
    ports:
      - "6379:6379"
