DROP TABLE IF EXISTS user;

CREATE TABLE IF NOT EXISTS user (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `userID` VARCHAR(255) NOT NULL,
  `userName` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;